source=~/.config/matugen/generated/mango-colors.conf

source=~/Arch-Dots/.config/mango/conf/monitors.conf
source=~/Arch-Dots/.config/mango/conf/environment.conf
source=~/Arch-Dots/.config/mango/conf/appearance.conf
source=~/Arch-Dots/.config/mango/conf/input.conf
source=~/Arch-Dots/.config/mango/conf/animations.conf
source=~/Arch-Dots/.config/mango/conf/decoration.conf
source=~/Arch-Dots/.config/mango/conf/autostart.conf
source=~/Arch-Dots/.config/mango/conf/rules.conf
source=~/Arch-Dots/.config/mango/conf/gestures.conf
source=~/Arch-Dots/.config/mango/conf/keybinds.conf
