repeat_rate=35
repeat_delay=250
numlockon=1

xkb_rules_layout=us,us

trackpad_natural_scrolling=1
trackpad_accel_speed=0.3
disable_while_typing=1
left_handed=0

mouse_natural_scrolling=0
mouse_accel_speed=0.1
left_handed=0
