keymode=common
bindl=SUPER+CTRL,Q,quit
bindl=SUPER,R,reload_config
bind=SUPER,C,killclient

keymode=default
bind=SUPER,T,spawn,uwsm-app -- kitty
bind=SUPER,B,spawn,uwsm-app -- zen-browser
bind=SUPER+SHIFT,B,spawn,uwsm-app -- zen-browser --private-window
bind=SUPER,E,spawn,uwsm-app -- kitty --class yazi -e yazi
bind=SUPER,X,spawn,uwsm-app -- grim -g "$(slurp)" - | swappy -f -
bind=SUPER,Z,spawn,uwsm-app -- kitty --class nvim -e nvim
bind=SUPER,Space,spawn,uwsm-app -- rofi -show drun
bind=SUPER,V,spawn_shell,uwsm-app -- cliphist list | rofi -dmenu | cliphist decode | wl-copy
bindls=SUPER,L,spawn,uwsm-app -- ~/.local/share/scripts/show_lock_screen.sh
bind=SUPER,H,spawn_shell,uwsm-app -- btop
bind=SUPER,Escape,spawn,uwsm-app -- rofi -show window
bind=SUPER,F11,togglefullscreen
bind=SUPER+SHIFT,F11,togglefakefullscreen
bind=SUPER+SHIFT,S,centerwin
bind=SUPER,D,togglefloating
bind=SUPER+SHIFT,D,dwindle_toggle_split_direction

bind=SUPER,Tab,focusstack,next
bind=SUPER,Up,focusdir,up
bind=SUPER,Down,focusdir,down
bind=SUPER,Left,focusdir,left
bind=SUPER,Right,focusdir,right
bind=SUPER+SHIFT,Up,smartmovewin,up
bind=SUPER+SHIFT,Down,smartmovewin,down
bind=SUPER+SHIFT,Left,smartmovewin,left
bind=SUPER+SHIFT,Right,smartmovewin,right
bind=SUPER+ALT,Up,smartresizewin,up
bind=SUPER+ALT,Down,smartresizewin,down
bind=SUPER+ALT,Left,smartresizewin,left
bind=SUPER+ALT,Right,smartresizewin,right
bind=SUPER+CTRL,Left,viewtoleft,0
bind=SUPER+CTRL,Right,viewtoright,0
bind=SUPER+CTRL+SHIFT,Left,viewtoleft_have_client,0
bind=SUPER+CTRL+SHIFT,Right,viewtoright_have_client,0
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0
bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0
bind=SUPER+CTRL+SHIFT,1,tagsilent,1,0
bind=SUPER+CTRL+SHIFT,2,tagsilent,2,0
bind=SUPER+CTRL+SHIFT,3,tagsilent,3,0
bind=SUPER+CTRL+SHIFT,4,tagsilent,4,0
bind=SUPER+CTRL+SHIFT,5,tagsilent,5,0
bind=SUPER+CTRL+SHIFT,6,tagsilent,6,0
bind=SUPER+CTRL+SHIFT,7,tagsilent,7,0
bind=SUPER+CTRL+SHIFT,8,tagsilent,8,0
bind=SUPER+CTRL+SHIFT,9,tagsilent,9,0

bind=SUPER+ALT,1,spawn,uwsm-app -- ~/.local/share/scripts/theme_selector.sh

binds=NONE,XF86MonBrightnessUp,spawn,swayosd-client --brightness raise
binds=NONE,XF86MonBrightnessDown,spawn,swayosd-client --brightness lower
binds=NONE,XF86AudioRaiseVolume,spawn,swayosd-client --output-volume raise
binds=NONE,XF86AudioLowerVolume,spawn,swayosd-client --output-volume lower
binds=NONE,XF86AudioMute,spawn,swayosd-client --output-volume mute-toggle
binds=NONE,XF86AudioMicMute,spawn,swayosd-client --input-volume mute-toggle
binds=NONE,XF86AudioNext,spawn,swayosd-client --playerctl next
binds=NONE,XF86AudioPlay,spawn,swayosd-client --playerctl play-pause
binds=NONE,XF86AudioPause,spawn,swayosd-client --playerctl play-pause
binds=NONE,XF86AudioPrev,spawn,swayosd-client --playerctl previous
binds=NONE,XF86Launch3,spawn,uwsm-app -- btop
binds=NONE,XF86Calculator,spawn,uwsm-app -- gnome-calculator

bind=SUPER+CTRL,R,spawn,uwsm-app -- wlr-randr --output eDP-1 --transform 90
bind=SUPER+CTRL+SHIFT,R,spawn,uwsm-app -- wlr-randr --output eDP-1 --transform 270
bind=SUPER+CTRL+SHIFT+ALT,R,spawn,uwsm-app -- wlr-randr --output eDP-1 --transform normal

bindls=SUPER,F7,toggle_monitor,eDP-1
bindls=SUPER,F8,spawn,enable_monitor,eDP-1

bind=SUPER,Equal,spawn,uwsm-app -- wtype -M ctrl plus -m ctrl
bind=SUPER,Minus,spawn,uwsm-app -- wtype -M ctrl minus -m ctrl
bind=SUPER,Backspace,spawn,uwsm-app -- wtype -M ctrl 0 -m ctrl

bind=SUPER,P,setkeymode,passthrough
keymode=passthrough
bind=SUPER+SHIFT,P,setkeymode,default
