windowrule=focused_opacity:1,isfullscreen:1

windowrule=force_tiled_state:0,appid:guifetch
windowrule=force_tiled_state:0,appid:yad
windowrule=force_tiled_state:0,appid:zenity
windowrule=force_tiled_state:0,appid:wev
windowrule=force_tiled_state:0,appid:org\.gnome\.FileRoller
windowrule=force_tiled_state:0,appid:file-roller
windowrule=force_tiled_state:0,appid:blueman-manager
windowrule=force_tiled_state:0,appid:com\.github\.GradienceTeam\.Gradience
windowrule=force_tiled_state:0,appid:feh
windowrule=force_tiled_state:0,appid:imv
windowrule=force_tiled_state:0,appid:system-config-printer
windowrule=force_tiled_state:0,appid:org\.quickshell
windowrule=no_force_center:0,appid:xwayland

windowrule=force_tiled_state:0,appid:kitty,title:nmtui
windowrule=width:1152,height:756,appid:kitty,title:nmtui
windowrule=no_force_center:0,appid:kitty,title:nmtui
windowrule=force_tiled_state:0,appid:org\.gnome\.Settings
windowrule=width:1344,height:864,appid:org\.gnome\.Settings
windowrule=no_force_center:0,appid:org\.gnome\.Settings
windowrule=force_tiled_state:0,appid:org\.pulseaudio\.pavucontrol|yad-icon-browser
windowrule=width:1152,height:756,appid:org\.pulseaudio\.pavucontrol|yad-icon-browser
windowrule=no_force_center:0,appid:org\.pulseaudio\.pavucontrol|yad-icon-browser
windowrule=force_tiled_state:0,appid:nwg-look
windowrule=width:960,height:648,appid:nwg-look
windowrule=no_force_center:0,appid:nwg-look

windowrule=force_tiled_state:0,title:(Select|Open)( a)? (File|Folder)(s)?
windowrule=force_tiled_state:0,title:File (Operation|Upload)( Progress)?
windowrule=force_tiled_state:0,title:.* Properties
windowrule=force_tiled_state:0,title:Export Image as PNG
windowrule=force_tiled_state:0,title:GIMP Crash Debug
windowrule=force_tiled_state:0,title:Save As
windowrule=force_tiled_state:0,title:Library

windowrule=force_tiled_state:0,title:Picture(-| )in(-| )[Pp]icture

windowrule=focused_opacity:1,title:krita|gimp|inkscape|darktable|resolve|kdenlive|shotcut|blender|godot

windowrule=force_tiled_state:0,appid:^(ueberzugpp_.*)$

windowrule=force_tiled_state:0,appid:steam,title:Friends List

windowrule=focused_opacity:1,appid:(steam_app_(default|[0-9]+))|gamescope

windowrule=force_tiled_state:0,appid:com-atlauncher-App,title:ATLauncher Console
windowrule=force_tiled_state:0,appid:PandoraLauncher,title:Minecraft Game Output

windowrule=noblur:1,appid:fusion360\.exe,title:Fusion360|(Marking Menu)
