source = ~/.config/matugen/generated/hyprland-colors.conf

general {
    gaps_in = $inner_gap
    gaps_out = $outer_gap
    gaps_workspace = $workspace_gap
    border_size = $border_size

    col.active_border = $primary
    col.inactive_border = $inverse_on_surface

    resize_on_border = true

    allow_tearing = false

    layout = dwindle
}

dwindle {
    pseudotile = true
    preserve_split = true
    smart_split = false
    smart_resizing = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true

    vfr = false

    animate_manual_resizes = false
    animate_mouse_windowdragging = false

    on_focus_under_fullscreen = 2
    allow_session_lock_restore = true
    middle_click_paste = false
    focus_on_activate = true
    session_lock_xray = true

    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
}

debug {
    error_position = 1
}
