exec-once = uwsm-app -- gnome-keyring-daemon --start --components=secrets
exec-once = uwsm-app -- /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = uwsm-app -- wl-paste --type text --watch cliphist store
exec-once = uwsm-app -- wl-paste --type image --watch cliphist store
exec-once = uwsm-app -- trash-empty 30
exec-once = uwsm-app -- hyprctl setcursor $cursor_theme $cursor_zize
exec-once = uwsm-app -- gsettings set org.gnome.desktop.interface cursor-theme '$cursor_theme'
exec-once = uwsm-app -- gsettings set org.gnome.desktop.interface cursor-size $cursor_size
exec-once = uwsm-app -- mpris-proxy
exec-once = uwsm-app -- xhost +si:localuser:root
exec-once = uwsm-app -- awww-daemon
exec-once = uwsm-app -- hypridle
exec-once = uwsm-app -- swayosd-server
exec-once = uwsm-app -- systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = uwsm-app -- dbus-update-activation-environment --systemd --all
exec-once = uwsm-app -- warp-cli connect
exec-once = uwsm-app -- hyprpm reload
