decoration {
    rounding = $window_rounding
    rounding_power = $window_rounding_power

    active_opacity = $active_opacity
    inactive_opacity = $inactive_opacity
    fullscreen_opacity = $fullscreen_opacity

    dim_inactive = true
    dim_strength = 0.2
    dim_special = 0.8

    shadow {
        enabled = $enable_shadows
        range = $shadow_range
        render_power = $shadow_power
        color = $primary
        offset = $shadow_offset
        scale = $shadow_scale
    }

    blur {
        enabled = $enable_blur
        size = $blur_size
        passes = $blur_passes
        new_optimizations = true
        ignore_opacity = true
        xray = $blur_xray
        vibrancy = $blur_vibrancy
        popups = $blur_popups
        input_methods = $blur_inputs
    }
}
