group {
    col.border_active = $on_primary
    col.border_inactive = $on_primary
    col.border_locked_active = $inverse_primary
    col.border_locked_inactive = $inverse_on_primary

    groupbar {
        font_family = JetBrains Mono NF
        font_size = 15
        gradients = true
        gradient_round_only_edges = false
        gradient_rounding = 5
        height = 25
        indicator_height = 0
        gaps_in = 3
        gaps_out = 3

        text_color = $primary
        col.active = $primary
        col.inactive = $on_primary
        col.locked_active = $inverse_primary
        col.locked_inactive = $inverse_on_primary
    }
}
