input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    numlock_by_default = true
    repeat_rate = 35
    repeat_delay = 250

    follow_mouse = 1
    focus_on_close = 1

    sensitivity = $mouse_sensitivity
    accel_profile = adaptive

    touchpad {
        natural_scroll = true
        disable_while_typing = $typing_disable_touchpad
        scroll_factor = $touchpad_sensitivity
    }

    left_handed = false
}

binds {
    allow_pin_fullscreen = true
    scroll_event_delay = 0
}

cursor {
    hotspot_padding = 1
}

device {
    name = epic-mouse-v1
    sensitivity = $mouse_sensitivity
}
