plugin:dynamic-cursor {
    enabled = true
    mode = tilt
    threshold = 2

    shaperule = clientside, none

    rotate {
        length = 20
        offset = 0
    }

    tilt {
        limit = 5000
        function = negative_quadratic
        window = 100
        full_tilt = 60
    }

    stretch {
        limit = 3000
        function = quadratic
        window = 100
    }

    shake {
        enabled = true
        nearest = true
        threshold = 0
        base = 4
        speed = 4
        influence = 0
        limit = 0
        timeout = 2000
        effects = false
        ipc = false
    }

    hyprcursor {
        nearest = true
        enabled = true
        resolution = -1
        fallback = clientside
    }
}

plugin:hyprglass {
    default_theme = dark
    default_preset = default

    brightness = 0.9
    dark:brightness = 0.82
    light:adaptive_boost = 0.5

    preset = name:clear, glass_opacity:0.8, blur_strength:1.5
    preset = name:clear:dark, brightness:0.7
    preset = name:clear:light, brightness:1.2
}

plugin:hyprtrails {
    color = $primary
}
