rootcolor={{colors.background.default.hex}}

bordercolor={{colors.outline_variant.default.hex}}
focuscolor={{colors.primary.default.hex}}
urgentcolor={{colors.error.default.hex}}

dropcolor={{colors.primary_container.default.hex}}
splitcolor={{colors.outline.default.hex}}

maximizescreencolor={{colors.tertiary.default.hex}}
scratchpadcolor={{colors.secondary_container.default.hex}}

globalcolor={{colors.primary_container.default.hex}}

overlaycolor={{colors.surface_container_high.default.hex}}
shadowscolor={{colors.shadow.default.hex}}
